# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Flat

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TickerFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TickerFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTickerFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TickerFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TickerFrame
    def Ticker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TickerFrame
    def Frame(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Flat.Line import Line
            obj = Line()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TickerFrame
    def FrameLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TickerFrame
    def FrameIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def TickerFrameStart(builder):
    builder.StartObject(2)

def Start(builder):
    TickerFrameStart(builder)

def TickerFrameAddTicker(builder, ticker):
    builder.PrependInt32Slot(0, ticker, 0)

def AddTicker(builder, ticker):
    TickerFrameAddTicker(builder, ticker)

def TickerFrameAddFrame(builder, frame):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(frame), 0)

def AddFrame(builder, frame):
    TickerFrameAddFrame(builder, frame)

def TickerFrameStartFrameVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFrameVector(builder, numElems: int) -> int:
    return TickerFrameStartFrameVector(builder, numElems)

def TickerFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return TickerFrameEnd(builder)
