# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class btDataFeedStub(object):
    """api

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalendarCall = channel.unary_stream(
                '/btDataFeed/CalendarCall',
                request_serializer=service__pb2.QuoteRequest.SerializeToString,
                response_deserializer=service__pb2.Calendar.FromString,
                _registered_method=True)
        self.InstrumentCall = channel.unary_stream(
                '/btDataFeed/InstrumentCall',
                request_serializer=service__pb2.QuoteRequest.SerializeToString,
                response_deserializer=service__pb2.InstFrame.FromString,
                _registered_method=True)
        self.LineStreamCall = channel.unary_stream(
                '/btDataFeed/LineStreamCall',
                request_serializer=service__pb2.QuoteRequest.SerializeToString,
                response_deserializer=service__pb2.TickFrame.FromString,
                _registered_method=True)
        self.AdjustmentStreamCall = channel.unary_stream(
                '/btDataFeed/AdjustmentStreamCall',
                request_serializer=service__pb2.QuoteRequest.SerializeToString,
                response_deserializer=service__pb2.AdjFrame.FromString,
                _registered_method=True)
        self.RightStreamCall = channel.unary_stream(
                '/btDataFeed/RightStreamCall',
                request_serializer=service__pb2.QuoteRequest.SerializeToString,
                response_deserializer=service__pb2.RightmentFrame.FromString,
                _registered_method=True)


class btDataFeedServicer(object):
    """api

    """

    def CalendarCall(self, request, context):
        """rpc CalendarCall(google.protobuf.Empty) returns (Calendar);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstrumentCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LineStreamCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustmentStreamCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RightStreamCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_btDataFeedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalendarCall': grpc.unary_stream_rpc_method_handler(
                    servicer.CalendarCall,
                    request_deserializer=service__pb2.QuoteRequest.FromString,
                    response_serializer=service__pb2.Calendar.SerializeToString,
            ),
            'InstrumentCall': grpc.unary_stream_rpc_method_handler(
                    servicer.InstrumentCall,
                    request_deserializer=service__pb2.QuoteRequest.FromString,
                    response_serializer=service__pb2.InstFrame.SerializeToString,
            ),
            'LineStreamCall': grpc.unary_stream_rpc_method_handler(
                    servicer.LineStreamCall,
                    request_deserializer=service__pb2.QuoteRequest.FromString,
                    response_serializer=service__pb2.TickFrame.SerializeToString,
            ),
            'AdjustmentStreamCall': grpc.unary_stream_rpc_method_handler(
                    servicer.AdjustmentStreamCall,
                    request_deserializer=service__pb2.QuoteRequest.FromString,
                    response_serializer=service__pb2.AdjFrame.SerializeToString,
            ),
            'RightStreamCall': grpc.unary_stream_rpc_method_handler(
                    servicer.RightStreamCall,
                    request_deserializer=service__pb2.QuoteRequest.FromString,
                    response_serializer=service__pb2.RightmentFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'btDataFeed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('btDataFeed', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class btDataFeed(object):
    """api

    """

    @staticmethod
    def CalendarCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/btDataFeed/CalendarCall',
            service__pb2.QuoteRequest.SerializeToString,
            service__pb2.Calendar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstrumentCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/btDataFeed/InstrumentCall',
            service__pb2.QuoteRequest.SerializeToString,
            service__pb2.InstFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LineStreamCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/btDataFeed/LineStreamCall',
            service__pb2.QuoteRequest.SerializeToString,
            service__pb2.TickFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustmentStreamCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/btDataFeed/AdjustmentStreamCall',
            service__pb2.QuoteRequest.SerializeToString,
            service__pb2.AdjFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RightStreamCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/btDataFeed/RightStreamCall',
            service__pb2.QuoteRequest.SerializeToString,
            service__pb2.RightmentFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
